services:
  andy-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: "3000"
      GATEWAY_URL: "http://localhost:8787"
      OPENAI_SECRET: "REVOKED_PLACEHOLDER"
      COMPLETE_MAX_USD: "0.00"
      MAX_PROMPT_CHARS: "4000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
