apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: pgdump-nightly
  namespace: coolbits
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: coolbits-ai:europe-west3:coolbits-rag-e
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      template:
        spec:
          containers:
            - name: pgdump
              image: europe-west3-docker.pkg.dev/coolbits-ai/containers/pgdump:v16-fixed
              command: ["/bin/bash", "/app/entrypoint.sh"]
              env:
                - name: INSTANCE_CONN
                  value: coolbits-ai:europe-west3:coolbits-rag-e
                - name: DBNAME
                  value: coolbits_rag
                - name: BUCKET
                  value: gs://coolbits-ai-sql-backups-ew3
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-password
                      key: latest
              volumeMounts:
                - name: cloudsql
                  mountPath: /cloudsql
                  readOnly: true
              resources:
                limits:
                  cpu: "1"
                  memory: 512Mi
          volumes:
            - name: cloudsql
              secret:
                secretName: cloudsql-instance-credentials
          restartPolicy: Never
          serviceAccountName: 271190369805-compute@developer.gserviceaccount.com
          timeoutSeconds: 3600
          maxRetries: 3
  launchStage: GA
