name: auth-smoke

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: coolbits-ai
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Verify gcloud auth
        run: |
          set -euo pipefail
          gcloud auth list
          gcloud config get-value project
          gcloud sts token-exchange --help >/dev/null 2>&1 || true
          gcloud run services list --region=europe-west3 --format='value(metadata.name)'
