name: Deploy Andy Gateway
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions: { id-token: write, contents: read }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ci-andygw@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud run deploy andy-gateway \
            --region europe-west3 \
            --source ./andy-src \
            --no-allow-unauthenticated \
            --quiet

      - name: Check status
        run: |
          gcloud run services describe andy-gateway --region europe-west3 \
            --format="value(status.latestCreatedRevisionName,status.trafficStatuses.status)"
